### ISSUE TITLE
Tradings file

### ISSUE THREAD

**Issue by mikeres0** [felixk42/Plus500TradesParser#1]
I understand that the program reads data from a file names `tradings`, which I'm guessing contains the instrument IDs of the instruments you'd like to track? 

Could you provide an example of the contents of this file? Is it in `.json` format? `.xml`?

Thanks in advance :+1:

**Comment by felixk42** [comment]
Hi Mike :) 
It's just copy and pasted (yeah with one's mouse...) from where the Plus500 web app generates trading reports on all of your closed trades. 
I have attached an example input file as well. 

Let me know if it doesn't work :) 

Cheers,
Felix

**Comment by mikeres0** [comment]
@felixk42 thanks a lot! I'd be interested in helping out with this repo if you're going to continue actively developing it :)

**Comment by felixk42** [comment]
@mikeres0 I haven't been day trading recently, and don't have a current plan to develop this further. 
Feel free to fork it if you would prefer that, or create pull requests. I would be interested in seeing where it goes. 

You may want to look into [QSTK](http://wiki.quantsoftware.org/index.php?title=QuantSoftware_ToolKit)  as well. I have been following the Cousera course on Computational Investing  (it's free I think) too.

**Comment by mikeres0** [comment]
@felixk42 I'll see how far I get on with my personal project first of all! Thanks though. I'll take a look at the QSTK stuff!
